# Defect Detection Dataset Configuration
# For YOLOv11m Training

# Dataset paths (update these to your actual paths)
path: C:/Users/RohithSuryaCKM/Downloads/Projects/Image_detection/dataset
train: images/train
val: images/val
test: images/test

# Class names - matching CVAT annotation labels
names:
  0: Good
  1: Flat_line
  2: Unwash

# Number of classes
nc: 3
